name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Execute every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Update Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake SVG
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: Rexaintreal
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy the generated SVG to the output branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
